version: "3.9"
services:
  mysql-zabbix:
    image: mysql:8.0
    container_name: mysql-zabbix
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    volumes:
      - /docker/volumes/mysql_data:/var/lib/mysql
    networks:
      - monitoring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: mysql-zabbix
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      mysql-zabbix:
        condition: service_healthy
    volumes:
      - /docker/volumes/zabbix_data:/var/lib/zabbix
    networks:
      - monitoring-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    container_name: zabbix-web
    restart: always
    environment:
      DB_SERVER_HOST: mysql-zabbix
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      PHP_TZ: America/Sao_Paulo

      ZBX_SERVER_HOST: zabbix-server   # 👈 ESSENCIAL
      ZBX_SERVER_PORT: 10051           # 👈 Porta padrão
    depends_on:
      - zabbix-server
    networks:
      - monitoring-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zabbix.rule=Host(`zabbix.marnep.com.br`) || Host(`192.168.56.50`)"
      - "traefik.http.routers.zabbix.entrypoints=web"
      - "traefik.http.routers.zabbix.middlewares=auth@file"

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-6.4-latest
    container_name: zabbix-agent
    restart: always
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - ZBX_HOSTNAME=zabbix-docker
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /docker/volumes/grafana_data:/var/lib/grafana
    networks:
      - monitoring-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.marnep.com.br`) || Host(`192.168.56.50`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.middlewares=auth@file"

networks:
  monitoring-network:
    external: true
