version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/volumes/portainer_data:/data
    networks:
      - monitoring-network

networks:
  monitoring-network:
    external: true
